Use threading instead of multiprocessing on Windows
multiprocessing isn't able to copy the socket on Windows: "AttributeError: 'module' object has no attribute 'fromfd'"