websockify: KeyError in wsproxy.py
The following exception is caused by 204675c85d08733d66c2dddb58ac6d5dcfedc11f
unbreak it by adding default value None.

> # ./utils/nova-novncproxy --config-file /etc/nova/nova.conf --web .
> Traceback (most recent call last):
>   File "./utils/nova-novncproxy", line 151, in <module>
>     wrap_cmd=None)
>   File "./utils/nova-novncproxy", line 78, in __init__
>     wsproxy.WebSocketProxy.__init__(self, *args, **kwargs)
>   File "/opt/stack/noVNC/utils/wsproxy.py", line 48, in __init__
>     self.unix_target    = kwargs.pop('unix_target')
> KeyError: 'unix_target'

Signed-off-by: Isaku Yamahata <yamahata@valinux.co.jp>